### ISSUE TITLE
Initial load at root should show an empty editor, and list of examples

### ISSUE THREAD

**Issue by danielcompton** [daiyi/demos#1]
When loading http://www.daiyi.co/demos/re-playground/, it would be good for it to have an empty editor, and a list of examples to view on the right hand side. Like this:

<img width="882" alt="screenshot of google chrome 19-07-17 10-41-20 am" src="https://user-images.githubusercontent.com/811954/28342923-d598864c-6c6e-11e7-9b08-5b5a95ef59b4.png">

It would also be nice if the list of code examples was immediately visible, rather than having to wait for the Klipse stuff to download, as that takes a long time with an empty cache.

**Comment by daiyi** [comment]
I think that, different from a language/repl editor (which you can test with expressions like `(+ 1 1)` and immediately get some feedback), a framework editor should have a minimal amount of boilerplate/template in place to let people get started with being able to do something with re-frame and/or reagent, because from a blank screen it's not clear how to inject reagent into the right-hand panel or see something happen. Like a "minimal template"?

maybe something like

```clojure
(ns hello.core
  (:require [reagent.core :as reagent]
            [re-frame.core :as re-frame]))

(defn ui
  []
  [:div 
   [:p "hello!"]])

(reagent/render 
  [ui]
  (js/document.getElementById "app"))
```

**Comment by danielcompton** [comment]
Sure, that's a good idea, I agree something minimal like that is good.

**Comment by daiyi** [comment]
hmm, come to think of it, I like your original suggestion better. it'll encourage people to look at samples first.   https://github.com/daiyi/demos/commit/f0af72b669df18a1c74d529b2f248309e9e823b0
